In [154]:
import numpy as np
import pandas as pd
import os
import csv
import cv2
import pickle
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import Normalizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt

In [155]:
brisk_trained = pd.read_csv("D:\College\SEM 5\CV\FinalBRISK.csv",header=None)
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)
f_data = clean_dataset(brisk_trained)

train_data = f_data


#assigning x the columns from 1 to 27 for training
x = train_data.iloc[:,0:16].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = train_data.iloc[:,16]
print("Y values")
print(y)


X values
[[0.05882353 0.02352941 0.02352941 ... 0.05882353 0.08235294 0.03529412]
 [0.03984064 0.0438247  0.06374502 ... 0.06374502 0.07171315 0.01195219]
 [0.06185567 0.02061856 0.1185567  ... 0.08762887 0.05154639 0.10309278]
 ...
 [0.08450704 0.04225352 0.02816901 ... 0.02816901 0.08450704 0.07042254]
 [0.0441989  0.05524862 0.0441989  ... 0.0441989  0.05524862 0.09392265]
 [0.04522613 0.05527638 0.05025126 ... 0.04522613 0.06030151 0.08542714]]
Y values
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
1216    1.0
1217    1.0
1218    1.0
1219    1.0
1220    1.0
Name: 16, Length: 1221, dtype: float64


In [157]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

In [158]:
import joblib

# Decision Tree


In [160]:
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model_dt = DecisionTreeClassifier(max_depth=13)
joblib.dump(model_dt,"model_dt")
#training the model with the Training Variables 
model_dt.fit(x_train, y_train)
#joblib.dump(model_dt,"model_dt")
#predicting the traget variable using testing variables
y_pred1 = model_dt.predict(x_test)
#Results
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")
print("Train Accuracy:",model_dt.score(x_train, y_train))
print("Test Accuracy:",model_dt.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred1, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred1, pos_label='positive', average='micro')) # true positive rate, Sensitivity
print("F2 Score: ",metrics.fbeta_score(y_test, y_pred1, pos_label='positive', average='micro', beta=2.0))
print("F1 Score: ",metrics.f1_score(y_test, y_pred1, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred1))

Decision Tree Results
Decision Tree Accuracy:  62.44897959183674 %
Train Accuracy: 0.9733606557377049
Test Accuracy: 0.6244897959183674
Precision Score:  0.6244897959183674
Recall Score:  0.6244897959183674
F2 Score:  0.6244897959183674
F1 Score:  0.6244897959183674
Confusion Matrix: 
[[110  43]
 [ 49  43]]


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro

# Random Forest

In [161]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators = 50)

model_rf.fit(x_train, y_train)
joblib.dump(model_rf,"model_rf")

y_pred2 = model_rf.predict(x_test)
print("Random Forest Clasifier")
print("Train Accuracy:",model_rf.score(x_train, y_train))
print("Test Accuracy:",model_rf.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred2,))

Random Forest Clasifier
Train Accuracy: 1.0
Test Accuracy: 0.689795918367347
Precision Score:  0.689795918367347
Recall Score:  0.689795918367347
F1 Score:  0.689795918367347
Confusion Matrix: 
[[141  12]
 [ 64  28]]


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# KNN

In [162]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors = 5)
model_knn.fit(x_train, y_train)
#joblib.dump(model_knn,"model_knn")
y_pred3 = model_knn.predict(x_test)
print("KNN")
print("Train Accuracy:",model_knn.score(x_train, y_train))
print("Test Accuracy:",model_knn.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred3, pos_label='positive', average='micro'))


KNN
Train Accuracy: 0.7725409836065574
Test Accuracy: 0.636734693877551
Precision Score:  0.636734693877551
Recall Score:  0.636734693877551
F1 Score:  0.636734693877551


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# SVM Linear

In [163]:
from sklearn import svm
model_svm_l = svm.SVC(kernel='linear', C=1, decision_function_shape='ovo')
model_svm_l.fit(x_train, y_train)
#joblib.dump(model_svm_l,"model_svm_l")
y_pred4 = model_svm_l.predict(x_test)
print("SVM Linear kernel")
print("Train Accuracy:",model_svm_l.score(x_train, y_train))
print("Test Accuracy:",model_svm_l.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred4, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred4, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred4, pos_label='positive', average='micro'))


SVM Linear kernel
Train Accuracy: 0.6875
Test Accuracy: 0.6244897959183674
Precision Score:  0.6244897959183674
Recall Score:  0.6244897959183674
F1 Score:  0.6244897959183674


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# SVM Sigmoid

In [164]:
from sklearn import svm
model_svm_s = svm.SVC(kernel='sigmoid', C=1, decision_function_shape='ovo')
model_svm_s.fit(x_train, y_train)
joblib.dump(model_svm_s,"model_svm_s")
y_pred5 = model_svm_s.predict(x_test)
print("SVM Sigmoid kernel")
print("Train Accuracy:",model_svm_s.score(x_train, y_train))
print("Test Accuracy:",model_svm_s.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred5, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred5, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred5, pos_label='positive', average='micro'))


SVM Sigmoid kernel
Train Accuracy: 0.6875
Test Accuracy: 0.6244897959183674
Precision Score:  0.6244897959183674
Recall Score:  0.6244897959183674
F1 Score:  0.6244897959183674


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# SVM POLY

In [165]:
from sklearn import svm
model_svm_p = svm.SVC(kernel='poly', degree=3, C=1, decision_function_shape='ovo')
model_svm_p.fit(x_train, y_train)
joblib.dump(model_svm_p,"model_svm_p")
y_pred6 = model_svm_p.predict(x_test)
print("SVM Poly kernel")
print("Train Accuracy:",model_svm_p.score(x_train, y_train))
print("Test Accuracy:",model_svm_p.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred6, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred6, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred6, pos_label='positive', average='micro'))

SVM Poly kernel
Train Accuracy: 0.8504098360655737
Test Accuracy: 0.6530612244897959
Precision Score:  0.6530612244897959
Recall Score:  0.6530612244897959
F1 Score:  0.6530612244897959


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# RBF

In [166]:
from sklearn import svm
model_svm_r = svm.SVC(kernel='rbf', gamma=1, C=1, decision_function_shape='ovo')
model_svm_r.fit(x_train, y_train)
joblib.dump(model_svm_r,"model_svm_r")
y_pred7 = model_svm_r.predict(x_test)
print("SVM RBF kernel")
print("Train Accuracy:",model_svm_r.score(x_train, y_train))
print("Test Accuracy:",model_svm_r.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred7, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred7, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred7, pos_label='positive', average='micro'))

SVM RBF kernel
Train Accuracy: 0.6875
Test Accuracy: 0.6244897959183674
Precision Score:  0.6244897959183674
Recall Score:  0.6244897959183674
F1 Score:  0.6244897959183674


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# GAUSSION NAVIE BAYES 

In [167]:
from sklearn.naive_bayes import GaussianNB
model_nb = GaussianNB().fit(x_train, y_train)
joblib.dump(model_nb,"model_nb")
y_pred8 = model_nb.predict(x_test)
print("Gaussian NB")
print("Train Accuracy:",model_nb.score(x_train, y_train))
print("Test Accuracy:",model_nb.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred8, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred8, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred8, pos_label='positive', average='micro'))

Gaussian NB
Train Accuracy: 0.7131147540983607
Test Accuracy: 0.6530612244897959
Precision Score:  0.6530612244897959
Recall Score:  0.6530612244897959
F1 Score:  0.6530612244897959


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# VOTING CLASSIFIER

In [168]:
from sklearn.ensemble import VotingClassifier

model_voting = VotingClassifier( estimators=[('DT', model_dt ), ('RF', model_rf),('KNN', model_knn), ('SCVP', model_svm_p), 
                                           ('GuassianNB', model_nb)], voting='hard')
model_voting.fit(x_train, y_train)
voting_pred = model_voting.predict(x_test)
joblib.dump(model_voting,"model_voting")
CM = confusion_matrix(y_test, voting_pred)
print("Voting Classifier Hard")
print("Train Accuracy:",model_voting.score(x_train, y_train))
print("Test Accuracy:",model_voting.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, voting_pred,pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, voting_pred,pos_label='positive', average='micro'))
print("F2 Score: ",metrics.fbeta_score(y_test, voting_pred,pos_label='positive', average='micro',beta=2.0))
print("F1 Score: ",metrics.f1_score(y_test, voting_pred,pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, voting_pred))

Voting Classifier Hard
Train Accuracy: 0.9077868852459017
Test Accuracy: 0.673469387755102
Precision Score:  0.673469387755102
Recall Score:  0.673469387755102
F2 Score:  0.673469387755102
F1 Score:  0.673469387755102
Confusion Matrix: 
[[136  17]
 [ 63  29]]


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro

PCA(n_components=13)

In [176]:
freak_trained = pd.read_csv("D:\College\SEM 5\CV\FinalFREAK.csv",header=None)
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)
f_data = clean_dataset(brisk_trained)

train_data = f_data


#assigning x the columns from 1 to 27 for training
x = train_data.iloc[:,0:16].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = train_data.iloc[:,16]
print("Y values")
print(y)

X values
[[0.05882353 0.02352941 0.02352941 ... 0.05882353 0.08235294 0.03529412]
 [0.03984064 0.0438247  0.06374502 ... 0.06374502 0.07171315 0.01195219]
 [0.06185567 0.02061856 0.1185567  ... 0.08762887 0.05154639 0.10309278]
 ...
 [0.08450704 0.04225352 0.02816901 ... 0.02816901 0.08450704 0.07042254]
 [0.0441989  0.05524862 0.0441989  ... 0.0441989  0.05524862 0.09392265]
 [0.04522613 0.05527638 0.05025126 ... 0.04522613 0.06030151 0.08542714]]
Y values
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
1216    1.0
1217    1.0
1218    1.0
1219    1.0
1220    1.0
Name: 16, Length: 1221, dtype: float64


In [177]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

In [178]:
import joblib

# Decision Tree

In [179]:
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model_dt = DecisionTreeClassifier(max_depth=13)
joblib.dump(model_dt,"model_dt")
#training the model with the Training Variables 
model_dt.fit(x_train, y_train)
#joblib.dump(model_dt,"model_dt")
#predicting the traget variable using testing variables
y_pred1 = model_dt.predict(x_test)
#Results
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")
print("Train Accuracy:",model_dt.score(x_train, y_train))
print("Test Accuracy:",model_dt.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred1, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred1, pos_label='positive', average='micro')) # true positive rate, Sensitivity
print("F2 Score: ",metrics.fbeta_score(y_test, y_pred1, pos_label='positive', average='micro', beta=2.0))
print("F1 Score: ",metrics.f1_score(y_test, y_pred1, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred1))

Decision Tree Results
Decision Tree Accuracy:  61.63265306122449 %
Train Accuracy: 0.9733606557377049
Test Accuracy: 0.6163265306122448
Precision Score:  0.6163265306122448
Recall Score:  0.6163265306122448
F2 Score:  0.6163265306122448
F1 Score:  0.6163265306122448
Confusion Matrix: 
[[113  40]
 [ 54  38]]


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro

# Random Forest

In [180]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators = 50)

model_rf.fit(x_train, y_train)
joblib.dump(model_rf,"model_rf")

y_pred2 = model_rf.predict(x_test)
print("Random Forest Clasifier")
print("Train Accuracy:",model_rf.score(x_train, y_train))
print("Test Accuracy:",model_rf.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred2,))

Random Forest Clasifier
Train Accuracy: 1.0
Test Accuracy: 0.6693877551020408
Precision Score:  0.6693877551020408
Recall Score:  0.6693877551020408
F1 Score:  0.6693877551020408
Confusion Matrix: 
[[140  13]
 [ 68  24]]


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# KNN

In [181]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors = 5)
model_knn.fit(x_train, y_train)
#joblib.dump(model_knn,"model_knn")
y_pred3 = model_knn.predict(x_test)
print("KNN")
print("Train Accuracy:",model_knn.score(x_train, y_train))
print("Test Accuracy:",model_knn.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred3, pos_label='positive', average='micro'))


KNN
Train Accuracy: 0.7725409836065574
Test Accuracy: 0.636734693877551
Precision Score:  0.636734693877551
Recall Score:  0.636734693877551
F1 Score:  0.636734693877551


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# SVM Linear

In [182]:
from sklearn import svm
model_svm_l = svm.SVC(kernel='linear', C=1, decision_function_shape='ovo')
model_svm_l.fit(x_train, y_train)
#joblib.dump(model_svm_l,"model_svm_l")
y_pred4 = model_svm_l.predict(x_test)
print("SVM Linear kernel")
print("Train Accuracy:",model_svm_l.score(x_train, y_train))
print("Test Accuracy:",model_svm_l.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred4, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred4, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred4, pos_label='positive', average='micro'))



SVM Linear kernel
Train Accuracy: 0.6875
Test Accuracy: 0.6244897959183674
Precision Score:  0.6244897959183674
Recall Score:  0.6244897959183674
F1 Score:  0.6244897959183674


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


546     0.061728
902     0.036866
1037    0.070796
422     0.057416
85      0.057851
          ...   
763     0.062857
835     0.054054
1216    0.079832
559     0.039326
684     0.043011
Name: 13, Length: 976, dtype: float64

# SVM Sigmoid

In [183]:
from sklearn import svm
model_svm_s = svm.SVC(kernel='sigmoid', C=1, decision_function_shape='ovo')
model_svm_s.fit(x_train, y_train)
joblib.dump(model_svm_s,"model_svm_s")
y_pred5 = model_svm_s.predict(x_test)
print("SVM Sigmoid kernel")
print("Train Accuracy:",model_svm_s.score(x_train, y_train))
print("Test Accuracy:",model_svm_s.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred5, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred5, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred5, pos_label='positive', average='micro'))


SVM Sigmoid kernel
Train Accuracy: 0.6875
Test Accuracy: 0.6244897959183674
Precision Score:  0.6244897959183674
Recall Score:  0.6244897959183674
F1 Score:  0.6244897959183674


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# SVM POLY

In [184]:
from sklearn import svm
model_svm_p = svm.SVC(kernel='poly', degree=3, C=1, decision_function_shape='ovo')
model_svm_p.fit(x_train, y_train)
joblib.dump(model_svm_p,"model_svm_p")
y_pred6 = model_svm_p.predict(x_test)
print("SVM Poly kernel")
print("Train Accuracy:",model_svm_p.score(x_train, y_train))
print("Test Accuracy:",model_svm_p.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred6, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred6, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred6, pos_label='positive', average='micro'))

SVM Poly kernel
Train Accuracy: 0.8504098360655737
Test Accuracy: 0.6530612244897959
Precision Score:  0.6530612244897959
Recall Score:  0.6530612244897959
F1 Score:  0.6530612244897959


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# SVM RBF

In [185]:
from sklearn import svm
model_svm_r = svm.SVC(kernel='rbf', gamma=1, C=1, decision_function_shape='ovo')
model_svm_r.fit(x_train, y_train)
joblib.dump(model_svm_r,"model_svm_r")
y_pred7 = model_svm_r.predict(x_test)
print("SVM RBF kernel")
print("Train Accuracy:",model_svm_r.score(x_train, y_train))
print("Test Accuracy:",model_svm_r.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred7, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred7, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred7, pos_label='positive', average='micro'))

SVM RBF kernel
Train Accuracy: 0.6875
Test Accuracy: 0.6244897959183674
Precision Score:  0.6244897959183674
Recall Score:  0.6244897959183674
F1 Score:  0.6244897959183674


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# GAUSSION NAVIE BAYES

In [186]:
from sklearn.naive_bayes import GaussianNB
model_nb = GaussianNB().fit(x_train, y_train)
joblib.dump(model_nb,"model_nb")
y_pred8 = model_nb.predict(x_test)
print("Gaussian NB")
print("Train Accuracy:",model_nb.score(x_train, y_train))
print("Test Accuracy:",model_nb.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred8, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred8, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred8, pos_label='positive', average='micro'))

Gaussian NB
Train Accuracy: 0.7131147540983607
Test Accuracy: 0.6530612244897959
Precision Score:  0.6530612244897959
Recall Score:  0.6530612244897959
F1 Score:  0.6530612244897959


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


# Voting Classifier

In [187]:
from sklearn.ensemble import VotingClassifier

model_voting = VotingClassifier( estimators=[('DT', model_dt ), ('RF', model_rf),('KNN', model_knn), ('SCVP', model_svm_p), 
                                           ('GuassianNB', model_nb)], voting='hard')
model_voting.fit(x_train, y_train)
voting_pred = model_voting.predict(x_test)
joblib.dump(model_voting,"model_voting")
CM = confusion_matrix(y_test, voting_pred)
print("Voting Classifier Hard")
print("Train Accuracy:",model_voting.score(x_train, y_train))
print("Test Accuracy:",model_voting.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, voting_pred,pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, voting_pred,pos_label='positive', average='micro'))
print("F2 Score: ",metrics.fbeta_score(y_test, voting_pred,pos_label='positive', average='micro',beta=2.0))
print("F1 Score: ",metrics.f1_score(y_test, voting_pred,pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, voting_pred))

Voting Classifier Hard
Train Accuracy: 0.9077868852459017
Test Accuracy: 0.6693877551020408
Precision Score:  0.6693877551020408
Recall Score:  0.6693877551020408
F2 Score:  0.6693877551020408
F1 Score:  0.6693877551020408
Confusion Matrix: 
[[137  16]
 [ 65  27]]


C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\prath\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro